### ISSUE TITLE
Exec Dashboard Exec-Analysis Issue

### ISSUE THREAD

**Issue by kuchanamounika** [hygieia/ExecDashboard#100]
Hi,

I am trying to install the execute dashboard, I am able to get the UI of it, but while configuring and running the executive analysis I am getting issue like below

2021-09-06 04:48:02.003 ERROR 22585 --- [taskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
java.lang.NoClassDefFoundError: Lcom/mongodb/MongoDriverInformation;
        at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_302]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[na:1.8.0_302]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[na:1.8.0_302]
        at org.apache.spark.util.SizeEstimator$.getClassInfo(SizeEstimator.scala:330) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.SizeEstimator$.visitSingleObject(SizeEstimator.scala:222) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.SizeEstimator$.org$apache$spark$util$SizeEstimator$$estimate(SizeEstimator.scala:201) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.SizeEstimator$.estimate(SizeEstimator.scala:69) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.collection.SizeTracker$class.takeSample(SizeTracker.scala:78) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.collection.SizeTracker$class.afterUpdate(SizeTracker.scala:70) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.collection.SizeTrackingVector.$plus$eq(SizeTrackingVector.scala:31) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:217) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1094) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1085) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1020) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1085) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:843) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.putSingle(BlockManager.scala:1406) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:123) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:88) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:62) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1482) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark.rdd(MongoSpark.scala:542) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark.toJavaRDD(MongoSpark.scala:561) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark$.load(MongoSpark.scala:362) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark.load(MongoSpark.scala) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.capitalone.dashboard.exec.config.DataFrameLoader.loadDataFrame(DataFrameLoader.java:21) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.collectCMDB(PortfolioCollector.java:218) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.collect(PortfolioCollector.java:149) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.run(PortfolioCollector.java:480) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_302]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_302]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]

my Analysis.properties like below

# MongoDB Details
dbname=analyticsdb
dbusername=analyticsuser
dbpassword=dbpassword
dbhostport=localhost:27017
logging.file=analysis.log
portfolio.cron=* * * * * *
portfolio.readUriUserName=dashboarduser
portfolio.readUriPassword=dbpassword
portfolio.readUriDatabase=localhost:27017/dashboarddb
portfolio.readUriPrefix=mongodb
portfolio.readDatabase=dashboarddb
portfolio.writeUri=mongodb://localhost:27017
portfolio.writeDatabase=analyticsdb
portfolio.filters=scm-commits:item:environment|production-incidents:severity:1.0|
#Enable/Disable SCM Collector
portfolio.scmCollectorFlag=true
#Enable/Disable Incident Collector
portfolio.incidentsCollectorFlag=false
#Enable/Disable Library Policy Collector
portfolio.libraryPolicyCollectorFlag=false
#Enable/Disable Static Code Collector
portfolio.staticCodeAnalysisCollectorFlag=true
#Enable/Disable Unit Test Collector
portfolio.unitTestCoverageCollectorFlag=false
#Enable/Disable AuditResult Collector
portfolio.auditResultCollectorFlag=false
#Enable/Disable Security Collector
portfolio.securityCollectorFlag=false
#Enable/Disable Performance Collector
portfolio.performanceCollectorFlag=false

my mongodb in localhost itself

Can some help me on resolve this issue please.

**Comment by ducdq1** [comment]
> Hi,
> 
> I am trying to install the execute dashboard, I am able to get the UI of it, but while configuring and running the executive analysis I am getting issue like below
> 
> 2021-09-06 04:48:02.003 ERROR

Add this dependency:

  
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.9.0</version>
        </dependency>
