### ISSUE TITLE
Unable to run the Hygieia executive analysis jar

### ISSUE THREAD

**Issue by AhireSwati** [Hygieia/ExecDashboard#79]
I downloaded the latest Hygieia Exec code yesterday.
I am getting below error when I try to run java -jar exec-analysis-1.0.0-SNAPSHOT.jar -Djasypt.encryptor.password=hygieiasecret --spring.config.location=../application.properties:
2020-04-29 16:35:02.617  INFO 4154 --- [taskScheduler-1] c.c.d.exec.collector.PortfolioCollector  : ##### Begin: collectCMDB #####
2020-04-29 16:35:02.753  INFO 4154 --- [taskScheduler-1] o.apache.spark.sql.internal.SharedState  : Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/opt/ExecDashboard/exec-analysis/target/spark-warehouse').
2020-04-29 16:35:02.754  INFO 4154 --- [taskScheduler-1] o.apache.spark.sql.internal.SharedState  : Warehouse path is 'file:/opt/ExecDashboard/exec-analysis/target/spark-warehouse'.
2020-04-29 16:35:02.767  INFO 4154 --- [taskScheduler-1] o.s.jetty.server.handler.ContextHandler  : Started o.s.j.s.ServletContextHandler@12abb0b3{/SQL,null,AVAILABLE,@Spark}
2020-04-29 16:35:02.767  INFO 4154 --- [taskScheduler-1] o.s.jetty.server.handler.ContextHandler  : Started o.s.j.s.ServletContextHandler@47fae00b{/SQL/json,null,AVAILABLE,@Spark}
2020-04-29 16:35:02.768  INFO 4154 --- [taskScheduler-1] o.s.jetty.server.handler.ContextHandler  : Started o.s.j.s.ServletContextHandler@9bb8ff{/SQL/execution,null,AVAILABLE,@Spark}
2020-04-29 16:35:02.768  INFO 4154 --- [taskScheduler-1] o.s.jetty.server.handler.ContextHandler  : Started o.s.j.s.ServletContextHandler@1b178f84{/SQL/execution/json,null,AVAILABLE,@Spark}
2020-04-29 16:35:02.770  INFO 4154 --- [taskScheduler-1] o.s.jetty.server.handler.ContextHandler  : Started o.s.j.s.ServletContextHandler@15b5c90{/static/sql,null,AVAILABLE,@Spark}
2020-04-29 16:35:03.449  INFO 4154 --- [taskScheduler-1] o.a.s.s.e.s.s.StateStoreCoordinatorRef   : Registered StateStoreCoordinator endpoint
2020-04-29 16:35:03.459  WARN 4154 --- [taskScheduler-1] o.apache.spark.sql.SparkSession$Builder  : Using an existing SparkSession; some configuration may not take effect.
2020-04-29 16:35:03.576  WARN 4154 --- [taskScheduler-1] org.apache.spark.storage.BlockManager    : Block broadcast_0 could not be removed as it was not found on disk or in memory
2020-04-29 16:35:03.582 ERROR 4154 --- [taskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.NoClassDefFoundError: Lcom/mongodb/MongoDriverInformation;
        at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_242]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[na:1.8.0_242]
        at java.lang.Class.getDeclaredFields(Class.java:1916) ~[na:1.8.0_242]
        at org.apache.spark.util.SizeEstimator$.getClassInfo(SizeEstimator.scala:330) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.SizeEstimator$.visitSingleObject(SizeEstimator.scala:222) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.SizeEstimator$.org$apache$spark$util$SizeEstimator$$estimate(SizeEstimator.scala:201) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.SizeEstimator$.estimate(SizeEstimator.scala:69) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.collection.SizeTracker$class.takeSample(SizeTracker.scala:78) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.collection.SizeTracker$class.afterUpdate(SizeTracker.scala:70) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.util.collection.SizeTrackingVector.$plus$eq(SizeTrackingVector.scala:31) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:217) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1094) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1085) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1020) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1085) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:843) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.storage.BlockManager.putSingle(BlockManager.scala:1406) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:123) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:88) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:62) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1482) ~[spark-core_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark.rdd(MongoSpark.scala:542) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark.toJavaRDD(MongoSpark.scala:561) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark$.load(MongoSpark.scala:362) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.mongodb.spark.MongoSpark.load(MongoSpark.scala) ~[mongo-spark-connector_2.11-2.3.3.jar!/:2.3.3]
        at com.capitalone.dashboard.exec.config.DataFrameLoader.loadDataFrame(DataFrameLoader.java:21) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.collectCMDB(PortfolioCollector.java:218) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.collect(PortfolioCollector.java:149) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.run(PortfolioCollector.java:488) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_242]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoDriverInformation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[na:1.8.0_242]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[exec-analysis-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[na:1.8.0_242]
        ... 39 common frames omitted

Here's my application.properties file:
dbname=analyticsdb
dbusername=analyticsuser
dbpassword=analyticspass
dbhostport=exec-db:27017

portfolio.cron=0 */5 * * * *

portfolio.readUriUserName=dashboarduser
portfolio.readUriPassword=dbpassword

portfolio.readUriDatabase=db:27017
portfolio.readUriPrefix=mongodb
portfolio.readDatabase=dashboarddb

portfolio.writeUri=mongodb://exec-db:27017
portfolio.writeDatabase=exec-db

#portfolio.incidentsCollectorFlag=true
portfolio.scmCollectorFlag=true
#portfolio.codeAnalysisCollectorFlag=true

**Comment by AhireSwati** [comment]
I added the below two dependencies in exec-analysis/pom.xml
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.10.2</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.11.12</version>
        </dependency>

Although these jars were getting used, the versions were different. Referred the below link for versions supported for mongo-spark-connector_2.11
The issue has been solved after adding the correct versions for dependencies in pom.xml

**Comment by AhireSwati** [comment]
hi\
