### ISSUE TITLE
Hygieia 3 Collector - Execution Issue

### ISSUE THREAD

**Issue by venkiradkris** [Hygieia/ExecDashboard#9]
Hi

I am getting below issue in Hygieia 3 Collector. At high level i can understand that it is expecting data from Hygieia 2 DB (dashboarddb).

Please suggest/guide that what would be the minimal expectation/dashboard/pipeline should be configured in Hygieia 2. First action in Hygieia 3 is selecting executive / portfolio. What does executive / portfolio means in Hygieia 2 in order to show data in Hygieia 3. 

2018-06-13 17:55:11.150 ERROR 31763 --- [taskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

org.apache.spark.sql.AnalysisException: cannot resolve '`validConfigItem`' given input columns: []; line 1 pos 176;
'Project ['_id AS productId#32, 'configurationItem AS productName#33, 'environments, 'components, 'businessOwner, 'ownerDept, 'appServiceOwner, 'supportOwner, 'developmentOwner]
+- 'Filter ((('validConfigItem = 1) && isnotnull('businessOwner)) && ('itemType = app))
   +- SubqueryAlias cmdb
      +- Relation[] MongoRelation(MongoRDD[7] at RDD at MongoRDD.scala:52,Some(StructType()))

        at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:88) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:85) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:279) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:289) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$6.apply(QueryPlan.scala:298) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:298) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:268) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:85) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:78) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:126) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$foreachUp$1.apply(TreeNode.scala:126) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.8.jar!/:na]
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:78) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:91) ~[spark-catalyst_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:52) ~[spark-sql_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:66) ~[spark-sql_2.11-2.2.0.jar!/:2.2.0]
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623) ~[spark-sql_2.11-2.2.0.jar!/:2.2.0]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.collectCMDB(PortfolioCollector.java:120) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.collect(PortfolioCollector.java:93) ~[classes!/:1.0.0-SNAPSHOT]
        at com.capitalone.dashboard.exec.collector.PortfolioCollector.run(PortfolioCollector.java:301) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

Regards
Venkat

**Comment by venkiradkris** [comment]
Hi - Please help for the above query. Thanks.

**Comment by Sbrenthughes** [comment]
You cmdb table doesn't contain a validConfigItem attribute in the document.

**Comment by subodhbattina** [comment]
@venkiradkris : 
As a general advise: 
Please go through the documentation for a better understanding of the product: https://hygieia.github.io/ExecDashboard/Introduction.html

1. cmdb document exists in "dashboarddb" database
2. You would need to first run the "hpsm-cmdb-collector" to be able to populate "cmdb" collection in "dashboarddb"

Here's the sample properties file for hpsm collector below:

hpsm.cron=0 0 1 * * *

hpsm.server=
hpsm.port=
hpsm.protocol=http
hpsm.resource=SM/7/ws/
hpsm.contentType=text/xml
hpsm.charset=UTF-8

hpsm.user=
hpsm.pass=

hpsm.appSubType=Application Service
hpsm.appType=
hpsm.appStatus=In Use,Archived,Being Decommissioned,Maintenance,In Stock,Reserved,Installed,In-Use

hpsm.compSubType=Business
hpsm.compType=application

hpsm.detailsRequestType=RetrieveDeviceListRequest
hpsm.detailsSoapAction=RetrieveList

hpsm.envSubType=Environment
hpsm.envType=bizservice

hpsm.changeOrderRequestType=RetrieveChangeListRequest
hpsm.changeOrderSoapAction=RetrieveList

hpsm.changeOrderDays=1
hpsm.changeOrderCron=0 */10 * * * *

hpsm.incidentRequestType=RetrieveIncidentListRequest
hpsm.incidentSoapAction=RetrieveList

hpsm.incidentDays=1
hpsm.incidentCron=0 */10 * * * *

3. Regarding your question below:
First action in Hygieia 3 is selecting executive / portfolio. What does executive / portfolio means in Hygieia 2 in order to show data in Hygieia 3

In Hygieia 2.0, you would need to create a dashboard and assign it to an appropriate Application (ASV), and a component (BAP). And depending on what type of metrics you want to see on hygieia-exec dashboard, you would need to create a supporting widget in Hygieia 2.0 for the data to be collected into "dashboarddb". Hygieia 3.0 collectors will then read that data from "dashboarddb" to generate your metrics. The metrics are then stored in "analysticsdb".

The executive/portfolio is really the owner of the Application, Component to which the dashboard is attached in Hygieia 2.0. Thanks

**Comment by matjukov-nikolaj** [comment]
@venkiradkris Have you solved this problem? How?

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/ExecDashboard/issues/19 checkout the information here.
