### ISSUE TITLE
MongoDriverInformation NoClassDef Error

### ISSUE THREAD

**Issue by larsen-mallick** [Hygieia/ExecDashboard#95]
I see the following error in exec-analysis application logs - 

2020-07-31 12:15:00.015  INFO 13264 --- [taskScheduler-1] c.c.d.exec.collector.PortfolioCollector  : ##### Begin: collectCMDB #####
2020-07-31 12:15:00.028  WARN 13264 --- [taskScheduler-1] o.apache.spark.sql.SparkSession$Builder  : Using an existing SparkSession; some configuration may not take effect.
2020-07-31 12:15:00.069  WARN 13264 --- [taskScheduler-1] org.apache.spark.storage.BlockManager    : Block broadcast_3 could not be removed as it was not found on disk or in memory

2020-07-31 11:40:27.712 ERROR 13264 --- [taskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.  
java.lang.NoClassDefFoundError: Lcom/mongodb/MongoDriverInformation;
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoDriverInformation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_232]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[exec-analysis-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_232]
        ... 39 common frames omitted

I think there's a mismatch in Mongo Driver dependency. 

I have the below dependency configured - 

<dependency>
            <groupId>org.mongodb.spark</groupId>
            <artifactId>mongo-spark-connector_2.11</artifactId>
            <version>${spark.version}</version>
        </dependency>

I have tried with spark version 2.3.3 and 2.42. 

The problem appears to be that package of the class - MongoDriverInformation has been changed from com.mongodb ot com.mongodb.client recently.

I see mongo-java-driver:3.4.3 in classpath.

**Comment by larsen-mallick** [comment]
This can be overcome by adding the below Maven dependency in executive-analysis\pom.xml - 

<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.12.5</version>
        </dependency>
